### ISSUE TITLE
A tale of two Mediums.

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/content-distribution#10]
Is there any reason to keep this live ?  https://tecommons.medium.com ![Screen Shot 2021-03-30 at 8.29.02 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/4b9c3e96-4059-426a-8593-52b29691b2c1)

When we have this one now?  https://medium.com/token-engineering-commons 
![Screen Shot 2021-03-30 at 8.29.28 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/328be733-2ccd-4ecc-8c3b-fb5f5cd409b4)

**Comment by markoprljic** [comment]
What I see here is that the first one https://tecommons.medium.com/ is the Author, like a medium user. 
The second one https://medium.com/token-engineering-commons is a medium page, like publications page. 

I'm not sure we should delete any of those especially if the first one (Author) is coming up first in google search.

The second one, the TEC Medium PAGE should just be customised design based on the Author page design, and all branding assets can be found here https://github.com/CommonsBuild/tec-branding-assets

**Comment by markoprljic** [comment]
@chuygarcia92 @natenatesoo Who's taking ownership of this issue? Any progress?

**Comment by chuygarcia92** [comment]
@markoprljic so far we think approaching this from an SEO perspective will be a better solution

**Comment by natenatesoo** [comment]
Yeah.  We are currently working on it within the SEO hack sessions.  We will maintain both pages.  SEO results will change over time, and we are developing a strategy for it.

**Comment by tamarandom** [comment]
This is under of umbrella of the larger SEO issue!! Closing.
