### ISSUE TITLE
Forum post for Disputable Voting's Challenge Amount

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#13]
@GriffGreen commented on [Sun Feb 28 2021](https://github.com/CommonsBuild/coordination/issues/477)

---

@freedumbs00 commented on [Mon Mar 08 2021](https://github.com/CommonsBuild/coordination/issues/477#issuecomment-792741002)

I'm assigning @divine-comedian.  We are not ready yet but you can prepare.  I will be adding you to more of these for the Upgrade.

**Comment by tamarandom** [comment]
Closing!
