### ISSUE TITLE
Article idea : Article about the Working Groups

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#15]
@tamarandom commented on [Tue Feb 16 2021](https://github.com/CommonsBuild/coordination/issues/434)

## 📋 Anything to add?

Article proposed by Sebnem, loop her into this. 

To be fleshed out but essentially : 
- Who are the working groups
- Why are the working groups
- How do they function?

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links

---

@tamarandom commented on [Fri Feb 19 2021](https://github.com/CommonsBuild/coordination/issues/434#issuecomment-782232705)

sync with @ataberkcasur on this.

**Comment by tamarandom** [comment]
Dropping this here, descriptions about the working groups to be used for YouTube (and also the website). 
https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by tamarandom** [comment]
@mount-manu will take this on. Woohoo!! This can make a really nice medium piece. 

cc: @natenatesoo @eduardovegap @liviade1

**Comment by mount-manu-zz** [comment]
Same as issue #1165: working on it, expecting to complete it by next week / first week of March (finally!)
