### ISSUE TITLE
0mega / WG category on the Forum

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#17]
@tamarandom commented on [Sat Feb 27 2021](https://github.com/CommonsBuild/coordination/issues/466)

## 📋 Anything to add?

 https://forum.tecommons.org/c/working-groups/13

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Done.
