### ISSUE TITLE
Share the Community Call video recording on Twitter every Friday

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/content-distribution#19]
As part of our transparency initiatives, we want to share the Community Call video recording on Twitter every Friday. This will be a weekly recurring tweet - same wording but new video every week. Does the Comms WG approve? 

Please let me know if you have suggestions to improve the draft below or if it's good to go. Thanks! :)

DRAFT:
Not able to join our Community Call yesterday? No problem. It’s on our YouTube channel. From the Praise fest start to our Working Group updates to the TE Project Spotlight at the end, they are always high vibe, good times! 🙌🗣️🌟
Watch now: https://www.youtube.com/watch?v=ehhAVtQhLAs 

Reviewer: @chuygarcia92 @markoprljic @divine-comedian 

cc: @Zeptimus

**Comment by markoprljic** [comment]
Good with me! :)

**Comment by divine-comedian** [comment]
here for example @iviangita if you want to tag the comms WG  you'll see an option to tag -  @CommonsBuild/communications  once you have a draft you can ping the @CommonsBuild/editingteam to come and review your draft. If it's helpful for you its there rather than having to think or lookup who to tag you can just tag whole teams

**Comment by divine-comedian** [comment]
**Propose:**

Not able to join our Community Call yesterday? No problem, it’s on our YouTube channel. From the Praise Fest to our Working Group updates to the TE Project Spotlight at the end, they are always high vibe, good times! raised_handsspeaking_headstar2
Watch now: https://www.youtube.com/watch?v=ehhAVtQhLAs

**Comment by iviangita** [comment]
@divine-comedian oohh thanks for the tagging tips and edits! I'll use your proposed wording. 🙏

**Comment by iviangita** [comment]
Closing this now and adding the edited content under issue [382](https://github.com/CommonsBuild/coordination/issues/382). Thanks guys! 🙏
