### ISSUE TITLE
Write forum post for how to get wxdai

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#20]
@divine-comedian commented on [Wed Apr 07 2021](https://github.com/CommonsBuild/coordination/issues/623)

how to get wxdai, what are the options, what are the STEPS? 

Try to get people to start from DAI or ETH but also if they have BTC or crypto on other chains

---

@divine-comedian commented on [Wed Apr 07 2021](https://github.com/CommonsBuild/coordination/issues/623#issuecomment-815153469)

first draft - https://docs.google.com/document/d/18557GJhhb7q7k3rYJ3cji8RgwUCnmf42rUpgporl65M/edit?usp=sharing

---

@divine-comedian commented on [Sun Apr 11 2021](https://github.com/CommonsBuild/coordination/issues/623#issuecomment-817405351)

@GriffGreen  @freedumbs00  review ready

**Comment by freedumbs00** [comment]
I forget we need to do these things...I like it.  @divine-comedian .

**Comment by divine-comedian** [comment]
@CommonsBuild/editingteam  please review

https://docs.google.com/document/d/18557GJhhb7q7k3rYJ3cji8RgwUCnmf42rUpgporl65M/edit?usp=sharing

**Comment by freedumbs00** [comment]
Closing this.  I liked it
