### ISSUE TITLE
T Wells' presentation for TEC

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#21]
There will be a sync call to review T Wells'  presentation for newcomers. Could work great as a landing page!

**Comment by markoprljic** [comment]
I sent all design resources to T Wells on Discord PM. If anything else needed please let me know.

**Comment by chuygarcia92** [comment]
@twell-s and I met earlier today and he will work on a proposal over the weekend. We'll have a hack sesh next week to catch up and see a WIP at a time @markoprljic can attend.

**Comment by chuygarcia92** [comment]
Update: @twell-s still working on a draft and reviewing documentation

**Comment by markoprljic** [comment]
From Discord convos...

T Wells is working on an onboarding module similar to the one he created for 1Hive https://docs.google.com/presentation/d/e/2PACX-1vQm_v90bEp-g04GoADuIAvbpEqwT6tatSXZOgYKGkhTQFjsLCZdqsJidYZdDPvLR4_muj1pyI7EsKdi/pub?start=false&loop=false&delayms=60000

He wanted to do the same for TEC and start with WGs in the same way he did Swarms for 1Hive - unless there is a different approach that better meets the needs of TEC.

Our starting point is categorization - how can we effectively group the WGs in a way that makes sense and enables easy access for new visitors/members. 

T Wells  first pass; feel free to comment - 
https://docs.google.com/document/d/1ct8K4AMqiHJHkF9NfkK03EaVacoLnecUJrDfkarhJXY/edit?usp=sharing
Nates Gitbook resources https://app.gitbook.com/@suits-nathan/s/tec-source/

Questions: 

Do we need a module designed to acquaint new members with the WG structure specifically, or something more broad?

Once we agree on a framework then perhaps we can talk more about how it could be integrated into the TEC site?

**Comment by markoprljic** [comment]
@chuygarcia92 I renamed this issue to reflect what's being done. You are assigned to carry this through. 
Pleas sync with TWells and Suga in Discord group.

First mockups TWells sent ...
https://docs.google.com/presentation/d/1hAlqKFzmjp6mWfpX8POJyeeOBEPSqQAVgtDEovrnbhk/edit?usp=sharing

**Comment by tamarandom** [comment]
Update from T wells on #comms channel :

Onboarding Module Drafts
w/ Categories: https://bit.ly/3biPrUk
w/out: https://bit.ly/3hiadHn
Feedback doc: https://bit.ly/3uEdIMa

**Comment by markoprljic** [comment]
Thanks for the update Tam. 
Thanks TWells for both versions.

I left feedback in the doc.

**Comment by tamarandom** [comment]
Done! The issue, #665,  to support T Wells covers the work from here.
