### ISSUE TITLE
Youtube description for each WG

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/content-distribution#23]
To promote our Youtube videos as part of transparency initiatives, can we request help from Comms WG to draft the verbiage or template to put in the description box of the WG videos - like one template for each WG? This can help with our SEO too if we use the right keywords. :)

**Comment by divine-comedian** [comment]
draft in progress - https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit?usp=sharing

**Comment by divine-comedian** [comment]
@CommonsBuild/editingteam @markoprljic   draft ready for review ^

**Comment by markoprljic** [comment]
@divine-comedian I think this is good! 

Would it be good to paste hashtags [from this list](https://github.com/CommonsBuild/coordination/issues/490#issuecomment-795400021) at the bottom of each channel description? I think it would be good.

**Comment by tamarandom** [comment]
@markoprljic @divine-comedian will you present this to the Stewards in our weekly on Wed so all can eyeball their section before it goes live on Youtube.

**Comment by markoprljic** [comment]
I believe the sections were sourced from their respective docs and forum groups, not sure that needs review from Stewards. 
Is that correct @divine-comedian 

We could run it through on the call to give final thumbs up tho or if anyone wants to add something.

**Comment by divine-comedian** [comment]
@tamarandom  @markoprljic 

I pulled all the info almost verbatim from the WG manifestos, ideally these are being kept up to date. 
I can add some hashtags no problem.

**Comment by markoprljic** [comment]
@divine-comedian Can we close this one or is there any other update?

**Comment by divine-comedian** [comment]
If we can assume all the @CommonsBuild/community-stewards  have tweaked or at least reviewed their youtube descriptions we can move this into publishing.

**Comment by divine-comedian** [comment]
@CommonsBuild/publicationteam

**Comment by markoprljic** [comment]
@CommonsBuild/community-stewards Did you get the chance to review your YT descriptions? Please respond with thumbs up when reviewed and good to be published. 

Here's the doc https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

Thanks.

**Comment by iviangita** [comment]
I'm closing this issue since we have already started using these descriptions in our Youtube channel. If there are changes needed, stewards can reach out to me and @Zeptimus. 

Here's the final document: https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit?usp=sharing
