### ISSUE TITLE
Hatch Campaigns  🥳  

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/content-distribution#24]
This is the last Sprint before the Hatch Sprint! Woohoo!

This issue is to create a strategic comms campaign leading up to and through the end of the Hatch.

Here are some off the cuff ideas I want to jot down but they are not carefully thought through yet so please can any of the ideas that are no good and make it great! 

*When* // *What* // *Where/Who*

10 & 5 days before the Hatch //  Trusted Seed activation CTA & ready wxDAI // Twitter, Discord & all our TG groups 
Hatch Day // EXCITING news //  Twitter, Discord & all our TG groups 
5 days after the Hatch // Update & Last chance // Twitter, Discord & all our TG groups 
1 day before the CLOSE of the Hatch // Last chance // Twitter, Discord & all our TG groups

**Comment by markoprljic** [comment]
@chuygarcia92 Do you feel comfortable taking on this Epic?

**Comment by markoprljic** [comment]
Thinking about what we need:

- Content producer for the campaign 
- Distribution schedule and channels 
- Supporting graphics and/or memes
- Link to the page to learn more, Sign up or get notified or other
- Updates during the Hatch (how we're doing)

Please fill in with other things needed.

**Comment by markoprljic** [comment]
I'd love some thoughts on this from @divine-comedian @natenatesoo and Anna Swan when she joins our github org :)

**Comment by markoprljic** [comment]
@MrsBadgerface FYI

**Comment by MrsBadgerface** [comment]
Can someone briefly share a couple of things so I have some context? 

1. What's the timescales for this? (When does the Hatching happen?)
2. What's the intention? (Goals and hopes of this campaign).
3. Who are we hoping to communicate with?

**Comment by divine-comedian** [comment]
yes as anna-marie mentioned above ^ We need some more context.

Hopefully we can battle-test our C&D board in this coming sprint. Has anyone been delegated to write the launch post? @markoprljic

**Comment by natenatesoo** [comment]
Yes, it looks like we will need content -- I would suggest Medium Articles.  I don't think they need to be complicated, very brief, but slinging resource links for Trusted Seed Application? (how late can this be done?), Swiss Membership dAPP, TEC Handbook (Hatcher FAQ), and links to our Parameter votes.  Distribution on the other hand will need to be highly targeted to as many different TE communities as possible, as well as a Tweet schedule for Ivy to utilize (possibly a tweet once a day?!)

To-Do List:

1. Identify exact date of Hatch Opening.

(I think we can do this with 2 medium articles)
2. Trusted Seed Activation and wxDAI article. (Can be general with 2 distribution phases at 10 & 5 days before the Hatch)
3. We are Hatching! article. (General with 3 distribution phases on day of, 5 days left, last day)
4. Compile a list of Discord Channels/Forums of relevant TE Communities (perhaps Hatcher Outreach WG can source a list from their Hatchers document?)
5. Create a Tweet Schedule for Ivy at each Distribution phase. 

Those are my thoughts at least.

**Comment by markoprljic** [comment]
@tamarandom You wanna fill in here as well?

**Comment by markoprljic** [comment]
@chuygarcia92 is coordinating this Epic.

**Comment by markoprljic** [comment]
We're organising a Hack Sesh for this epic. 
@natenatesoo will add it to the TEC calendar and invite Craig and EVERYONE is welcome to join.

**Comment by MrsBadgerface** [comment]
Hey @markoprljic Was the session set up? I had a look at the calendar today and couldn't see anything that looked like it would be related to this but perhaps I'm missing it?

**Comment by markoprljic** [comment]
> Hey @markoprljic Was the session set up? I had a look at the calendar today and couldn't see anything that looked like it would be related to this but perhaps I'm missing it?

Good question! I'm not sure, @natenatesoo should be able to answer.

**Comment by tamarandom** [comment]
Backlog refinement. Closing this Epic!
