### ISSUE TITLE
Create a post that explains how to use the Hatch Dashboard and include Hatch Param Parties dates

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#26]
@GriffGreen commented on [Fri Apr 16 2021](https://github.com/CommonsBuild/coordination/issues/649)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
https://docs.google.com/document/d/1yp1lHM3Ksx3OoBCaHF6uktNN186rGT22S0GfD_u3qoE/edit# - draft 

it's missing some info for the hatch param parties, also feel free to suggest any narrative changes (your economy, your choice etc..)
@CommonsBuild/parameters-commons-swarm  @CommonsBuild/editingteam

**Comment by divine-comedian** [comment]
https://docs.google.com/document/d/1yp1lHM3Ksx3OoBCaHF6uktNN186rGT22S0GfD_u3qoE/edit# 

draft ready for review - hoping for a quick review then off to the forum, this one is past due! 

@CommonsBuild/editingteam  @CommonsBuild/communications

**Comment by MrsBadgerface** [comment]
@divine-comedian Went through it quickly with my editor hat on. Hope that helps. Really fascinating to read! Helping me get some insight into what was talked about at the params party last night. Thank you.

**Comment by divine-comedian** [comment]
published- https://forum.tecommons.org/t/design-your-economy-make-your-choice/366

**Comment by tamarandom** [comment]
Closing.
