### ISSUE TITLE
Update Gravity WG YouTube descriptions

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#28]

**Comment by chuygarcia92** [comment]
Update content descriptions in playlist videos:
https://youtube.com/playlist?list=PLusWL9gf0FIRU-QqtwBqIDQnG3NqisJ-l

Description drafts can be found here: https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by danelsuga** [comment]
took a stab: 

https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by JuankBell** [comment]
**Sorry for the delay! Text updated!**

Gravity

The Gravity Working Group aims to help maintain equilibrium and well-being in decentralized communities through nonviolent communication, transformational approach to conflicts, and a system that provides easy access to management protocols.

We foster dialogue for smooth coordination, prevention and solution of social issues in DAOs, and train participants to become conflict management agents, called “Gravitons”.

Steward: Juan (JuankBell)
Calendar: Weekly sync on Thursdays after TEC community call.

**Comment by chuygarcia92** [comment]
Thanks @JuankBell!! DONE!
