### ISSUE TITLE
Update Hatch Outreach WG YouTube descriptions

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#29]

**Comment by chuygarcia92** [comment]
Update content descriptions in playlist videos:
https://youtube.com/playlist?list=PLusWL9gf0FIRM3Dd-p7Tt8oLVWDX51R23 

Description drafts can be found here: https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by tamarandom** [comment]
Proposing something short and to the point! Asked @eduardovegap for his input on this before we can close it! 

The Hatch Outreach working group is responsible for reaching out to Hatchers, building relationships with projects and helping guide them in submitting their proposals for funding. 

Find us on the #hatch-outreach channel on our Discord.

**Comment by tamarandom** [comment]
@eduardovegap approved version 👍🏽 👍🏽

The Hatch Outreach working group is responsible for reaching out to Hatchers and helping guide projects to submit proposals for funding. Find us on the #hatch-outreach channel on our Discord.


Updating the doc now ...
