### ISSUE TITLE
Content for Join our Community page on TEC Website

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/content-distribution#3]
We need content for the TEC Website, it is a dedicated page to redirect users to Join our Community. This is where onboarding begins. 

Related issue in TEC Web repo https://github.com/TECommons/tec-web/issues/8

**Comment by divine-comedian** [comment]
first draft ready for review - Any other places we should direct people? Is the gitbook ready for the public? @CommonsBuild/community-stewards  https://docs.google.com/document/d/1AJCAv5CA_5NmEg3T6LOHz40-YzJ9uDf5bkCxFeHE-tA/edit?usp=sharing

**Comment by jessicazartler** [comment]
Looks awesome! You could also link to https://forum.tecommons.org/t/5-how-to-join-contribute/98 or work in the working groups / some of the content, you could also add or embed the TE community Gcalendar with this link https://calendar.google.com/calendar/u/0/embed?src=5mkep1ad1j860k6g7i7fr8plq0@group.calendar.google.com&ctz=Europe/Berlin

Nice work!

**Comment by tamarandom** [comment]
Update : Closed
