### ISSUE TITLE
Update Soft-Gov WG YouTube descriptions

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#30]

**Comment by chuygarcia92** [comment]
Update content descriptions in playlist videos:
https://youtube.com/playlist?list=PLusWL9gf0FISS5VA7p50ohoyb9Rf5HzoY 

Description drafts can be found here: https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by tamarandom** [comment]
@liviade1, @Zeptimus will take a shot at this and share for approval.

**Comment by danelsuga** [comment]
took a stab: 

https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by Zeptimus** [comment]
Thanks Katy, closing
