### ISSUE TITLE
Update Transparency WG YouTube descriptions

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#33]

**Comment by chuygarcia92** [comment]
Update content descriptions in playlist videos:
https://youtube.com/playlist?list=PLusWL9gf0FIQ_sbCfiB2e7PkPWkgpetX4 

Description drafts can be found here: https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by Zeptimus** [comment]
We did it :D 

This is the Transparency Working Group! We help promote transparency, openness and mutual monitoring as the high-level ideal that we're moving towards at TEC. The way that we get there is by empowering people to share this experience with the Transparency Audits and making information available to everyone.
We gather every two weeks on Mondays at 3pm CET. Check out our agenda and notes: https://docs.google.com/document/d/1jbuqlIXd3s9gRwXbT9ND0zUbE0MaEP9EyO6sHY46iOY/edit 

Join us! 
Edit: Can be close. i cant do it myslef

**Comment by tamarandom** [comment]
Impossible! You're a TEC 🐳!  

Check your perms now, should be fixed.
