### ISSUE TITLE
Update YouTube descriptions for each video uploaded

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#37]
The idea is to use these descriptions for each video + a template that includes main links:

- Discord server

- Twitter

- Glossary (for newcomers)

https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by chuygarcia92** [comment]
this is already going on with each upload, is this right @Zeptimus ?

**Comment by tamarandom** [comment]
Yep, just confirmed with @Zeptimus. Closing.
