### ISSUE TITLE
Share MVV Runoff on Twitter

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/content-distribution#38]
Hey team, I prepared the draft tweets for MVV Runoff: one to send tomorrow (or today if possible) and another one on Monday for the last call. Can someone review/approve them before I publish? Just also a reminder that Twitter has limited characters. :D Thank you!!! 🙏

cc: @liviade1 

- [x] Review/approve draft tweets (Comms team)
- [x] Share on Twitter (Ivy)

**First announcement:**

The Top 3 MVV Runoff is ON!⚡

Vote for your fave Mission, Vision & Values statements & make your mark in our Cultural Build! 🗳

Deadline: Apr 27, 1pm EST / 7pm CET⏰

VOTE HERE: https://tokenlog.xyz/CommonsBuild/TokenLog-SoftGov

How to vote: https://youtu.be/2vQ1ZdBpv5U 

Know more: https://forum.tecommons.org/t/mvv-runoff-vote-now/348 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/5b2b438e-4349-4223-884f-38eeb4a5c62a) **_- this is a gif_** 

**Second announcement:**

🔔 LAST CALL!

Vote for your favorite MVV statements before April 27, 1pm EST / 7pm CET to participate in TEC's governance!

VOTE HERE: https://tokenlog.xyz/CommonsBuild/TokenLog-SoftGov 

How to vote: https://youtu.be/2vQ1ZdBpv5U   

Know more: https://forum.tecommons.org/t/mvv-runoff-vote-now/348  

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/a896c5ba-2747-43b0-af45-7f52a7633fd1)

**Comment by divine-comedian** [comment]
Comments: 

 - In the first announcement the GIF seems particularily HUGE, maybe it's just a github formatting issue.. 
 - The youtube link for both posts have a timestamp on it so when you click on the link it takes you to the end of the video.

**Comment by iviangita** [comment]
@divine-comedian Github made the GIF so huge haha but here's the link to the meme I found on our Discord server https://discord.com/channels/810180621930070088/810180622165213222/827636946003427368. I also updated the Youtube link - thanks for catching that! Is there anything else that needs to change? Otherwise I'll go ahead and publish them.  :)

**Comment by divine-comedian** [comment]
Looks good to me Ivi! Moving to publishing

**Comment by markoprljic** [comment]
Mitch 🔥🔥🔥

**Comment by iviangita** [comment]
Thanks so much @divine-comedian!!!! 🙏😊 It's already published so I'm closing this issue. :)

https://twitter.com/tecmns/status/1385633564671180802?s=20
