### ISSUE TITLE
Praise Quant Blog v2

### ISSUE THREAD

**Issue by cranders1** [CommonsBuild/content-distribution#39]
Greetings C&D. Not sure if the biweekly PQ blog should be included in this repo/process. 
Given recent Comms convergence, however, can't hurt to throw it to the collective wolves to decide.
Duplicate w/ [#220 ](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/220)

Here's a draft. Hack away. 
https://docs.google.com/document/d/1WobIOMjad_bcSdf9qn23QlWRP2xV1iGqZB09VikJtEs/edit?usp=sharing

Info requests for @GriffGreen  @danelsuga
Own language or a link or a no go will work. 

Also a draft in Medium w/ intact formatting etc
https://medium.com/p/4f7c9fb42d99/edit

**Comment by tamarandom** [comment]
Good idea to move it here. Closing out the old issue : https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/220

**Comment by natenatesoo** [comment]
Looks Awesome!

**Comment by cranders1** [comment]
published w/o mvv final but did link to github repo with a promise of a polished release soon.
pinged ivy.

https://docs.google.com/document/d/1WobIOMjad_bcSdf9qn23QlWRP2xV1iGqZB09VikJtEs/edit#heading=h.n962ilictkf1

https://medium.com/token-engineering-commons/your-economy-your-choice-v2-4f7c9fb42d99

**Comment by danelsuga** [comment]
@cranders1 @GriffGreen - here is the PQ blog for April 24 - May 8. Could you please have a peek before I publish? Thank you!

One specific question (@GriffGreen ?) is to make sure I've got the right folks listed for the Commons Swarm AMA: Griff, Chuy, Sem, Fabi [CORRECT?] and Luke Duncan (https://www.youtube.com/watch?v=VpkM46h5g5g)

https://docs.google.com/document/d/1sxKkpOMu1JpcC76EFARFriYgbSTHTwpCbpYIYy9RCJs/edit

https://medium.com/p/81fa5efc242c/edit

Thank you!

**Comment by cranders1** [comment]
nice work @danelsuga. comments provided.

**Comment by tamarandom** [comment]
And... it's live! https://medium.com/token-engineering-commons/params-voting-final-hatch-demo-81fa5efc242c

**Comment by danelsuga** [comment]
I've got a draft floating around if anyone wants to check it out today. Thx. 

@tamarandom 
@liviade1 
@GriffGreen 
@cranders1

**Comment by danelsuga** [comment]
@sembrestels or some one else in the know, could you please help me add info for the Hatch Demo segment?

E.g., what is being tested? What is important to include/share about this last demo with the community?

Thx!

**Comment by tamarandom** [comment]
With link ;) 

https://docs.google.com/document/d/1YDUFGzebYv7whJgpOnqfHENRU7G7RUitt-L4V4-o0Ms/edit

**Comment by tamarandom** [comment]
Thanks @danelsuga !! It looks great.

**Comment by danelsuga** [comment]
Hi gang! Here is the draft for the blog. Please share your edits **before** Wednesday. Thank you so much!

https://docs.google.com/document/d/1GWf5G33v3SPtkNkatIbu6zDYCYnjvYIl2Oo4AjzqWyk/edit?usp=sharing

@tamarandom 
@cranders1 
@liviade1 
@GriffGreen

**Comment by cranders1** [comment]
looks amaze at first glance. will provide comments this afternoon (PDT)🙂

**Comment by tamarandom** [comment]
Had a 1-over & made some suggestions. I wager @cranders1 will have more good input. It's excellent work @danelsuga!

**Comment by danelsuga** [comment]
It's published!

https://medium.com/token-engineering-commons/hatch-prep-and-what-you-can-do-to-help-42dd81ad183c

**Comment by danelsuga** [comment]
Published: https://medium.com/token-engineering-commons/heating-up-to-the-hatch-ea0fea993b50

**Comment by danelsuga** [comment]
https://medium.com/token-engineering-commons/the-final-sprint-to-the-hatch-153be7c26c4

**Comment by GriffGreen** [comment]
Wow! yeah ! glad to se this coming back!

**Comment by tamarandom** [comment]
Heh, sorry, it was just me brining closed issues back to life because of their #repeating tag. I'm re-closing them all now.

**Comment by tamarandom** [comment]
Heh, sorry, it was just me brining closed issues back to life because of their #repeating tag. I'm re-closing them all now.
