### ISSUE TITLE
Hatch DAO Content for Landing page

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/content-distribution#4]
### Context

We want to productize the “Hatch DAO” (it is modifiable and customizable) we should give the Hatch DAO that credit, think of it as a product. 

Create a dedicated page on the website to promote the Hatch DAO, link to resources for people to get started
“New way to do DAO’s, this is how you should do it!”
Mention legal aspect and what they can reuse and / or not use. 

### Requirement

We need content for the landing page where we want to promote the Hatch DAO. Think of it as a modern landing page where we promote the product and want people to "download" or "Sign up" for it, but we'll give them other resources to start using it. 
It should speak about:

- What is the Hatch DAO?
- How it works?
- How can I use it for my community?
- Where do I start?

### Resources

Hatch TL;DR https://docs.google.com/document/d/1Ji2vV5c_PCXt2q0G-1wTddyOaUp5ESKWht2UKcoE7S0/edit
How to become a hatcher https://docs.google.com/document/d/1tsEPNb-gLEh9FKOGLBPt0prfWrOwjmnnjtPdCpy8lxo/edit

**Comment by markoprljic** [comment]
Reviewers and Editors: Params, Comms, and the requestor of the issue.
Maybe have labels for each WG this falls under.

**Comment by markoprljic** [comment]
Postponing this until further notice.

**Comment by chuygarcia92** [comment]
any thoughts on this @divine-comedian @markoprljic ?

https://hackmd.io/@1sBtuDmrRBG360k8-EXf2A/BJ6JtQku_

**Comment by chuygarcia92** [comment]
I'm also working on an animated video with @mount-manu but we'll share script & storyboard with all of you before doing any production

**Comment by markoprljic** [comment]
I'm getting 404 on Hackmd doc. @chuygarcia92

**Comment by Zeptimus** [comment]
Next monday Lauren Manu and Zep will bring a draft and this issue should get done next week

**Comment by chuygarcia92** [comment]
@laurenluz has drafted this amazing document for the hatch landing page:

https://hackmd.io/@X8tRdfwBQVago2RXal2LDg/HyKXHO2Ou/edit 

This is still a WIP but to complement it we're taking in account the following:

- Asking Commons Swarm to have a collapsable tree with an FAQ

- @divine-comedian is working on updating [Jake's forum post](https://forum.tecommons.org/t/ragequit-delay-and-what-it-means/130?u=chuygarcia92) on ragequitting to include in the FAQ.

**Comment by chuygarcia92** [comment]
this is @divine-comedian 's update on ragequit:

https://forum.tecommons.org/t/ragequitting-ragequit-delay-and-how-they-work/130/41

**Comment by laurenluz** [comment]
I updated the FAQ section. Would love some feedback or QA:

https://hackmd.io/SBKMAE56QruvHr1ZRUangw?both

@chuygarcia92 

FYI - just so everyone knows, the FAQ section can and will be collapsible 😉

**Comment by divine-comedian** [comment]
reviewed! left a comment

**Comment by laurenluz** [comment]
Thanks Mitch - I updated based on your comment. @chuygarcia92 - is this good to go now? what's the next step?

**Comment by chuygarcia92** [comment]
I think we're done, we would just need a link to Joe's final Miro in the FAQ. I understand this will be ready this week @tamarandom ?

**Comment by tamarandom** [comment]
The "TEC is live" version is still under iteration, it's close though!!

This is the TEC 2-phases! There might be one minor change made this week but let's not let that hold this up. Can run with this now. 
[TEC Hatch 2-phase process - final.pdf](https://github.com/CommonsBuild/content-distribution/files/6572401/TEC.Hatch.2-phase.process.-.final.pdf)

**Comment by chuygarcia92** [comment]
This is done and ready for implementing in the hatch front end.
@sembrestels @PJColombo @GriffGreen 

https://hackmd.io/SBKMAE56QruvHr1ZRUangw?both

**Comment by PJColombo** [comment]
This looks great guys! 

I added it to the hatch front end.

@chuygarcia92 Do we have the animated video ready as well ?

**Comment by sembrestels** [comment]
The hatch content is already in place. I did some minor modifications that can be seen in the hackmd (it appears as underlined highlighted in green color), especially specifying that the voting will be available one week after the hatch is successful.
