### ISSUE TITLE
Param Party Medium Article

### ISSUE THREAD

**Issue by natenatesoo** [CommonsBuild/content-distribution#44]
Modify this Forum Post and transfer it into a Medium Article:  https://forum.tecommons.org/t/evolving-economics-via-hatch-param-parties/364

**Comment by tamarandom** [comment]
It's live! 

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

@danelsuga drafted it and incorporated feedback from Chuy, Jeff, Griff and myself. Excellent work @danelsuga !!!

There was some fiddling around with how to publish it on Medium but we finally figured it out.

**Comment by danelsuga** [comment]
Looking good! Thanks for all the help, everyone, esp Tam!!

**Comment by tamarandom** [comment]
Shared this tweet with @iviangita to be sent today: 


What are you doing this weekend? Want to learn all about the Hatch params and even submit your own set?

It’s your economy, your choice.

Next one starts soon...

Saturday: 7pm CET, 1pm EST, 10am PST
Sunday: 9 & 10pm CET, 3 & 4pm EST, 12 & 1pm PST

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

**Comment by tamarandom** [comment]
@GriffGreen updated this article with the debate sessions! So I'm leaving this in the distribution pipeline for sharing.

 ![Screen Shot 2021-05-11 at 11.46.42 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/570c0afe-0e72-4fe7-b4ca-536c4ef6c82d)

**Comment by danelsuga** [comment]
Tackled on May 7!

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

Closing. :)

**Comment by danelsuga** [comment]
Tackled on May 7!

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

Closing. :)

**Comment by danelsuga** [comment]
Tackled on May 7!

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

Closing. :)

**Comment by danelsuga** [comment]
Article tackled on May 7 with some follow-up edits and tweets on final voting and debates through the week (til Thursday). Voting ended today so closing now. :)

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

**Comment by danelsuga** [comment]
Article tackled on May 7 with some follow-up edits and tweets on final voting and debates through the week (til Thursday). Voting ended today so closing now. :)

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

**Comment by danelsuga** [comment]
Article published on May 7 with some follow-up edits and tweets on final voting and debates through the week (til Thursday). Voting ended today so closing now. :)

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281
