### ISSUE TITLE
Add Katy (Suga) to the C&D repo

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#45]
@markoprljic could you please give Katy permissions to create issues in this workspace?

danel.suga@gmail.com

**Comment by markoprljic** [comment]
Invited her to this repo

![Image 2021-05-06 at 5 50 29 pm](https://user-images.githubusercontent.com/5704285/117328533-0360cb00-ae94-11eb-9222-11bb25ead17c.jpg)

Also added her to Comms team in the org github

![Image 2021-05-06 at 5 53 29 pm](https://user-images.githubusercontent.com/5704285/117328574-0e1b6000-ae94-11eb-9de2-bf5e6e05791d.jpg)
