### ISSUE TITLE
Draft tweet for params party video and distribute

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/content-distribution#46]
Here's the link to the video: https://www.youtube.com/watch?v=qLlfPdbb8NY

**Comment by iviangita** [comment]
@CommonsBuild/communications @CommonsBuild/editingteam  For review/approval please before I publish, thanks! :) 

**DRAFT TWEET:**

The TEC is laying the groundwork for a bottom-up economy by allowing our community to propose and vote on its parameters before the Hatch. Deep dive into our economic design process in this Params Party with TE thought leaders @mZargham and @trentmc0!

https://youtu.be/qLlfPdbb8NY 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/ece29956-ab20-4ad9-8e3a-fd3553718204)

**Comment by danelsuga** [comment]
Looks great, Ivy. Thanks. My only comment is that @tamarandom was thinking maybe that video should be called a "sounding board" and not a params party?

**Comment by iviangita** [comment]
@danelsuga got it! Will ask her during our call later, thanks Katy! :D

**Comment by iviangita** [comment]
Hi @GriffGreen can you also please take a look and let me know if the video and tweet are good to go? Thank you! :)

**Comment by GriffGreen** [comment]
looks good

**Comment by iviangita** [comment]
Closing! 

https://twitter.com/tecmns/status/1392138930045083652?s=20
