### ISSUE TITLE
draft tweet for param party debates!! 

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#49]
Param Party DEBATES are starting Wednesday May 12 at 9am EST. Debate on Hatch Proposals with other TEC members. Champion your hatch design or a fork that you truly believe is the best.  

Challenge others to back up their DAO decisions and be prepared to defend yours! 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/28a748a2-bb51-4ce7-9d67-97d7790d0d67)

**Comment by iviangita** [comment]
Hi @divine-comedian! I turned it into 2 tweets so we can include the Discord link and the schedule. Please check and let me know what you think :D

@CommonsBuild/communications @CommonsBuild/editingteam For review/approval please before I publish, thanks! :) 

**(Part 1)**

Param Party DEBATES are starting TODAY! Debate on Hatch Proposals with other TEC members. 

Champion your hatch design, challenge others to back up their DAO decisions and be prepared to defend yours! 🏆

Know more here: https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/3cf9619f-a821-4509-bbc3-7cf021da3328)

**(Part 2)**

Check out the schedule of our Param Party Debates and join at your most convenient time! 📆 

Happening on our Discord - Parameters voice channel: https://discord.gg/NYaBbjTqh8 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/4f74a232-0a48-4c12-adcb-aca5f05ba0b5)

**Comment by divine-comedian** [comment]
PROPOSE:

**(Part 1)**

Param Party DEBATES are starting TODAY! Debate on Hatch Proposals with other TEC members. 

Champion your Hatch design, challenge others to back up their DAO decisions and be prepared to defend yours! 🏆

Know more here: https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/3cf9619f-a821-4509-bbc3-7cf021da3328)

**(Part 2)**

Find out when the Param Party Debates are happening.  Don't miss out, join one or join all of them! 📆 🙋

Happening on our Discord - Parameters voice channel: https://discord.gg/NYaBbjTqh8 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/4f74a232-0a48-4c12-adcb-aca5f05ba0b5)

**Comment by iviangita** [comment]
Thanks @divine-comedian, appreciate the edits! I'll schedule it on Tweetdeck to go out today :)

**Comment by iviangita** [comment]
Closing! https://twitter.com/tecmns/status/1392434388701380614?s=20
