### ISSUE TITLE
Draft tweet for this week's blog post 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/content-distribution#50]
@iviangita would it be ok for you to take on the tweet for the weekly blog post? 

https://medium.com/token-engineering-commons/params-voting-final-hatch-demo-81fa5efc242c

**Comment by iviangita** [comment]
Hi @tamarandom sure, we have a template for the TEC Blog Post tweet - it looks like this. Will send it out today :)

📰TEC NEWS - Everything you need to know in 5 min:

🗳️ Voting on the Params 
⏰ Commons Swarm Weekly Update
🙌 Impact Hour Leaderboard

Read it now: https://medium.com/token-engineering-commons/params-voting-final-hatch-demo-81fa5efc242c

**Comment by tamarandom** [comment]
Beautiful!
