### ISSUE TITLE
Vote dates announcement

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/content-distribution#51]
Key vote dates:

Primary vote of Hatch config params ends on Thursday, May 13.
Run-off vote of top-voted params ends on Thursday, May 20.

**Comment by iviangita** [comment]
@CommonsBuild/communications @CommonsBuild/editingteam requesting help with the wording :D

**DRAFT tweet for the primary vote - to be released today May 12th**

TIME TO VOTE for your favorite parameters and be a part of designing our token economy!  🗳️

Submit your votes before MAY 13, 8pm CET. Results will be announced during our Community Call. ⚡

Vote here: https://tokenlog.xyz/CommonsBuild/TEC-Hatch-Vote 

Latest updates: https://medium.com/token-engineering-commons/params-voting-final-hatch-demo-81fa5efc242c 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/a6d48f48-ad9d-42c1-a194-793bd8581764)

**DRAFT tweet for the run-off vote**

open to suggestions

**Comment by divine-comedian** [comment]
Looks great Ivi!

**Comment by iviangita** [comment]
Thanks @divine-comedian! Sending out the primary vote today :)

**Comment by tamarandom** [comment]
Beautiful!!

@iviangita so we can close this one now, right?
