### ISSUE TITLE
Create a Content map for TEC

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/content-distribution#52]
Create a page to be published on Gitbook or elsewhere that holds evergreen content of TEC. Similar to https://www.notion.so/giveth/Commons-Stack-Content-Map-f572a1a856f84f4e99e5847d7b18efe7

Related discussion https://github.com/CommonsBuild/coordination/issues/145

**Comment by markoprljic** [comment]
@chuygarcia92 We're looking for contributors here? Is it ok if I assign you to take the lead on this?

**Comment by Razga** [comment]
Nice, I could help out but I need to read more.

Edit: On it.

**Comment by chuygarcia92** [comment]
@razga (ZER8) has been working on a notion, here's the WIP:

https://www.notion.so/Token-Engineering-Commons-Content-Map-780f0275c5c54f74b797429f58379bc0

**Comment by Razga** [comment]
This is my semi-final version: 
https://www.notion.so/Token-Engineering-Commons-Content-Map-780f0275c5c54f74b797429f58379bc0

**Comment by Razga** [comment]
@chuygarcia92 DId you take a look at the content map?:D

**Comment by iviangita** [comment]
@chuygarcia92 can I also request access to the content map? we might need it for the selection of articles/documents to be translated :)

**Comment by chuygarcia92** [comment]
this is being reviewed by the Translations T.E.A.M. since it's a great starting point for the index they need. Some of the suggested content for translations is also included in issue #904

**Comment by tamarandom** [comment]
Closing! This is ongoing work now: https://www.notion.so/Token-Engineering-Commons-Content-Map-780f0275c5c54f74b797429f58379bc0
