### ISSUE TITLE
Animated video 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/content-distribution#55]
## 📋 Anything to add?

Chuy to fill in the details 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by chuygarcia92** [comment]
Hello everyone! Here are the 2 scripts we've been working on for the animated videos. Please make sure to post your reviews/feedback ASAP so we can jump into production.

The first spot is intended to be targeted to wider audiences, both community members and external people. We're trying to cover as many assets as possible! These will be re-used in animated spots with specific purposes, like the hatch and commons upgrade for example.
![TEC_spot02.png](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/5ced7fe0-4f3d-4391-9831-7720eed89f6b)

The second spot is gonna be used for the Hatch. It is aimed to people who are able to donate wxDai at this stage: CSTK token hodlers and Builders.
![TEC_hatchspot04-1.png](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/3ce2b949-1618-467b-9058-34c4ffab1b76)
![TEC_hatchspot04-2.png](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/f2191259-2f03-4c0a-aa59-8841188f5426)

**Comment by chuygarcia92** [comment]
Here's the latest update. Share your thoughts! We'd like to jump into production this week.

![TEC_hatchspot05-1.png](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/1b12a0c0-9552-4e2f-9967-21b3344309c2)

![TEC_hatchspot05-2.png](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/565724f1-076a-4be8-a0d5-2b563f68aeff)

**Comment by danelsuga** [comment]
I know there was talk about the significance of using "donate". Can it not just be "send" (wxDAI)?

I was also wondering if "to create a bright future for societies" could be changed slightly. Perhaps something like:

"to promote positive economic change for societies"

**Comment by chuygarcia92** [comment]
This is our production script:
[https://app.zenhub.com/files/349409011/192c8291-e4ac-427f-b052-1b6e4d969da1/download](https://app.zenhub.com/files/349409011/192c8291-e4ac-427f-b052-1b6e4d969da1/download)

**Comment by chuygarcia92** [comment]
Update on storyboard:

![TEC Storyboard1-3.png](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/23dd1adb-764d-49da-89f1-2b6d9c50e06f)

**Comment by tamarandom** [comment]
Update: Expected to be ready by Monday.

**Comment by tamarandom** [comment]
(via Zep...)
Looping in @knobsdao for advice process. 

Current Hatch Video script


0 - 0:03
Welcome to the Token Engineering Commons’s Hatch!

0:04 - 0:10
We are advancing the field of Token Engineering to promote positive, economic change for societies.

0:12 - 0:21
Token Engineering is all about validating economic design — before a bridge is built, it must be tested to ensure its safety.

0:22 - 0:30
Similarly, an economy is like a bridge in that its design needs to be validated and tested for resilience.

0:32 - 0:42
For this we need Token Engineering. As a member of the Trusted Seed, you can help the advancement of this critical field by joining the Hatch.

0:43 - 1:00
In the Hatch, an amount of wrapped xDAI will be sent by the Trusted Seed. Whenever anyone sends wrapped XDAI to the Hatch, Hatch tokens are minted. If we don’t reach the minimum goal, all of the wrapped xDAI will be refunded.

1:01 - 1:17
With Hatch tokens, the community will be able to participate in the Hatch DAO and help collectively design the economy for the Commons Upgrade. The Token Engineering Commons will fund proposals that will improve research, development and education in the field.

1:18 - 1:21
Token Engineering Commons — advancing Token Engineering!

1:24
Video ends

**Comment by natenatesoo** [comment]
Update: Final Version almost ready.

**Comment by chuygarcia92** [comment]
The hatch animation video is up & running, will now start the campaign around it so I'll close this issue.

https://youtu.be/7uGy_KNr2rk
