### ISSUE TITLE
Phrasing clarification about about CSTK tokens

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/content-distribution#6]
Content modification request! 

We need to change the following phrasing everywhere it exists. 

The known places are : 
1. at the bottom of all of the blog post
2. the forum
3. (maybe) inside the transparency doc

There may be other so keep a look out for it & use the new phrasing going forward. 

The old phrasing is "Token Engineering Commons members are also eligible to receive CSTK tokens from the Commons Stack for their Impact Hours."

The new phrasing is "Token Engineering Commons members are also eligible to receive CSTK tokens from the Commons Stack for their Praise they receive."

**Comment by natenatesoo** [comment]
This is a good point.  I think that changes to phrasing or terminology should be proposed within a TEC StyleGuide Document that is utilized by our group of Editors when editing new content.  I am currently working on this and will keep you updated.

**Comment by tamarandom** [comment]
Style Guide 👏🏼👏🏼

In the mean time, going back and editing the published blog posts is a piece of work of medium priority.
https://medium.com/token-engineering-commons/transparency-in-daos-999b17b0ff74

**Comment by natenatesoo** [comment]
Done!

**Comment by tamarandom** [comment]
Hey @natenatesoo This issue is still open so I want to check in whether it's ok to close and make sure you have access to close it yourself. (let me know if not, I just had to do that for Zep in the new C&D repo!)

**Comment by tamarandom** [comment]
Closing!
