### ISSUE TITLE
Update Rage Quit Forum Post

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#61]
Updating Ragequit post - https://forum.tecommons.org/t/ragequit-delay-and-what-it-means/130 with addendum reflecting how other hatch parameters (including hatch tribute) will affect this mechanism. Add any other relevant links to help users navigate to other important information.

**Comment by divine-comedian** [comment]
Forum post updated with additions by Nate and myself. 
https://forum.tecommons.org/t/ragequitting-ragequit-delay-and-how-they-work/130
@CommonsBuild/editingteam

**Comment by chuygarcia92** [comment]
thanks @divine-comedian and @natenatesoo 

this is the final update: https://forum.tecommons.org/t/ragequitting-ragequit-delay-and-how-they-work/130/41?u=chuygarcia92
