### ISSUE TITLE
Tweet series about the hatch TL;DR and hatch process

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#63]
Create tweets for the coming weeks informing the general community at large about the hatch process, how the hatch works and get people reading our forum content so the understand what the heck is going on!!

forum posts - 

https://forum.tecommons.org/t/how-you-can-hatch-the-tec/328

https://forum.tecommons.org/t/the-hatch-tl-dr/272

and create memes to correspond with tweets.

**Comment by divine-comedian** [comment]
MEMES! 
<a href="https://imgflip.com/i/5b5ziz"><img src="https://i.imgflip.com/5b5ziz.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by iviangita** [comment]
Here are the tweets:

https://twitter.com/tecmns/status/1401212971230011392?s=20 

https://twitter.com/tecmns/status/1400437612893151241?s=20

CLOSING! :D
