### ISSUE TITLE
Tweet series about how to get wxDai

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/content-distribution#64]
create tweets to blast out for the coming weeks to inform people about wxDai and how to get it so they are ready to contribute to the hatch! 

forum post- 
https://forum.tecommons.org/t/how-to-get-wxdai-a-bridging-story/347

and make moar memes to correspond!

**Comment by divine-comedian** [comment]
MEMES! 

<a href="https://imgflip.com/i/5b5xjw"><img src="https://i.imgflip.com/5b5xjw.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

<a href="https://imgflip.com/i/5b60nn"><img src="https://i.imgflip.com/5b60nn.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by iviangita** [comment]
DONE! https://twitter.com/tecmns/status/1401918620972683273?s=20
