### ISSUE TITLE
TEC C&D Request - Campaign for Community video

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#65]
**1- What is the content?**
- [ ] Graphic
- [ ] Meme
- [ ] Tweet
- [ ] Campaign for a specific event
- [ ] Article/Blog Post
- [x] Videos, Podcasts, Spotlight Interviews, etc.
- [ ] News (Recaps, mailing lists, etc)

**2- When is the distribution of this content due?**
10 days before the hatch

**3- What is the purpose of this content?**
- [X] Informative
- [ ] Call-To-Action (focused on community)
- [X] Engage/Invite (meant for wider audiences outside TEC & friends)

**4- Is this content finished?**
- [X] Yes
- [ ] No, it needs to be made

**5- Additional notes**
Shoutout to @mount-manu for all the hard work behind this video!

**Comment by tamarandom** [comment]
Update: @chuygarcia92 says close, we close!
