### ISSUE TITLE
Review: Forum post - Introduction to the Augmented Bonding Curve

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#68]
Progress by @divine-comedian: 

https://hackmd.io/Qey8zQxaRUyY_o4SLi-kBA

**Comment by divine-comedian** [comment]
hey @chuygarcia92  this is the dashboard spec, not the forum post. I believe @natenatesoo  is writing the forum post for the ABC.

**Comment by chuygarcia92** [comment]
This has been uploaded for a while, so I'm closing this issue:

https://forum.tecommons.org/t/augmented-bonding-curve-an-introduction-to-the-abc/497?u=chuygarcia92
