### ISSUE TITLE
Review: Forum post - Entry Tribute & Exit Tribute

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#69]
Progress by @natenatesoo: 

https://docs.google.com/document/d/1CCgyHTRCSouFbrQEZGhSZ5lqijWkvgSr3eIBH6BOsCo/edit?usp=sharing

**Comment by tamarandom** [comment]
@GriffGreen you want to greenlight this before we close it? Here is the link: https://forum.tecommons.org/t/augmented-bonding-curve-entry-exit-tribute/494

**Comment by tamarandom** [comment]
closing
