### ISSUE TITLE
Disribution of Z's article "The Importance of Token Engineering Ethics for the TEC"

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/content-distribution#7]
Strategic distribution for Zargham's article, which is soon to be published on our TEC Medium page. After it's published, we need to mega-amplify  it on Twitter, in our newsletter, share it with partner/ecosystem blogs and newsletters, etc.

**Comment by tamarandom** [comment]
It just went live! 
https://medium.com/token-engineering-commons/engineering-ethics-in-web3-18d981278018

**Comment by markoprljic** [comment]
And so this is where the distribution process need to kick in. I recall there was a list of channels and partners for distribution that Jess shared in another repo. @natenatesoo do you happen to have it?

**Comment by tamarandom** [comment]
FYI that for Twitter : Ivy and I crafted a tweet that went out after we had Jeff's feedback on it. It's a high profile piece so want to make sure the message is on exactly point. (Would not normally need Jeff's eyes on any other tweets.)

**Comment by natenatesoo** [comment]
I am unaware of this list, however I will talk to Jessica about it/search the repos.  I have discussed the distribution of content to partners and other channels with Ivy, and we are asyncing to establish a strategy around that, and will be incorporated within the Comprehensive C&D Document.

**Comment by markoprljic** [comment]
@natenatesoo This is the original process that Jess passed on us https://github.com/commonsbuild/coordination/issues/516#issuecomment-794260076

Pasting here for reference.

The piece must be appropriate for the channel and the message should not be spammy, something tailored to the group that is why people in that group would care. Would also be great to have different people taking on different channels to post so not all comes from one person.

Here are the main channels - this can be built out - but again, depends on the piece. We could also have sharing templates for people to do one on one sharing for friends/colleagues for pieces that are specifically of interest to them. Ideally need a contributor to lead these efforts, get more organized/process/templates for this - a content sharing network with our partner projects would be wonderful.

Here are the main channels I usually distribute in:

- [ ]  TEC news blog
- [ ]  TEC general discord
- [ ]  TEC Twitter
- [ ]  ask CS to RT
- [ ]  Commons Stack Telegram
- [ ]  cadCAD forum
- [ ]  cadCAD telegram channel
- [ ]  Partner channels: 1Hive, MetaGame, Whaler DAO
- [ ]  CS newlsetter
- [ ]  TEC newsletter (could be developed)

**Comment by tamarandom** [comment]
Update : Closing!
